services:
  postgres:
    image: postgres:16-alpine
    container_name: ragshield-postgres
    environment:
      POSTGRES_USER: ragshield
      POSTGRES_PASSWORD: ragshield
      POSTGRES_DB: ragshield
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ragshield -d ragshield"]
      interval: 5s
      timeout: 5s
      retries: 10

  qdrant:
    image: qdrant/qdrant:v1.12.4
    container_name: ragshield-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrantdata:/qdrant/storage

volumes:
  pgdata:
  qdrantdata:
